### ISSUE TITLE
Flattened/Minified json file cannot be parsed

### ISSUE THREAD

**Issue by bric3** [yamafaktory/jql#120]
I have a very big json file that was flattened / minified to a single line, and I would like to explore this document, however `jq` don't work and neither does `jql`.

```shell
$ jql --raw-output '.' aggregate-raw.json
Invalid JSON file or content
```

That would be nice if JQL could process this document.

**Comment by yamafaktory** [comment]
Hi @bric3 !

If I got it right, both `jq` and `jql` can't process your file, correct?

If true, would you mind sharing it? Are you sure the file is valid JSON? Depending on how big the file is, maybe you can try something like https://jsonlint.com.

N.B.: the best would be to share this file so that I can check it but I assume that it might be not possible?

**Comment by bric3** [comment]
@yamafaktory Hi yes that is the case, also yes I know this file is valid, as it is correctly processed by other tools.

While trying things I have found a smaller document that is parsed with `jq`, but not with `jql`. This file is somehow private. How should I share it with you ?

**Comment by yamafaktory** [comment]
@bric3 I checked against your file and indeed it fails (the error is swallowed by `jql` which display a dummy one, but that's intended). The issue is that `serde-json` has a recursion limit set by default. it simply crashes with your file. Hopefully, there's a feature in order to disable this behavior and some additional code. I've created a PR and will soon release a new version.

**Comment by yamafaktory** [comment]
@bric3 the new version has been released 🚀.

Feel free to ping me if something is not working as expected (apart from something that needs a `serde-json` fix of course).

**Comment by bric3** [comment]
@yamafaktory Thanks I'll try this !

**Comment by bric3** [comment]
So it works well, even on some bigger document !!!
Thank you very much
