### ISSUE TITLE
ranges on top-level arrays are not handeled properly

### ISSUE THREAD

**Issue by dym-sh** [yamafaktory/jql#35]
### data-input

(shortened from `https://api.github.com/orgs/tauri-apps/repos?per_page=100&type=sources`):

``` json
[
  {
    "id": 196701619,
    "node_id": "MDEwOlJlcG9zaXRvcnkxOTY3MDE2MTk=",
    "name": "tauri",
    "full_name": "tauri-apps/tauri",
    "html_url": "https://github.com/tauri-apps/tauri",
    "open_issues_count": 55,
    "forks": 51,
    "open_issues": 55,
    "watchers": 1629,
    "default_branch": "dev"
  },
  {
    "id": 206315614,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMDYzMTU2MTQ=",
    "name": "examples",
    "full_name": "tauri-apps/examples",
    "html_url": "https://github.com/tauri-apps/examples",
    "open_issues_count": 7,
    "forks": 4,
    "open_issues": 7,
    "watchers": 6,
    "default_branch": "master"
  }
]
```

### example of the bug

``` sh
jql '[0]."name"' org.json
"tauri"

jql '[0:]."name"' org.json
Node "name" not found on parent range [0:]
```

**Comment by yamafaktory** [comment]
@dym-sh thanks for the report, I'll have a look at it asap!

**Comment by yamafaktory** [comment]
@dym-sh After some debugging I finally came up with a solution: this is a normal behavior.
Let me explain why: you're trying to use a range selector on an array which is totally fine indeed. However a range selector, no matter if it's bounded or not - e.g. `[0:1]`, `[:1]` or `[1:]` - will always return an array!

If think the confusion lies in the fact that in `jql '[0]."name"' org.json` you have `[0]` which is a singleton index selection (https://github.com/yamafaktory/jql#index-selection). In this case you get back what is at index 0, which is an object.

With the range selector, `"name"` can't be found since you get back an array. You would need to the following:
```sh
jql '[0:].[0]."name"' org.json
jql '[0:][0]."name"' org.json # also valid
```
I did a quick check at how `jq` handle that (https://stedolan.github.io/jq/) and it also returns an array.
I'd tend to think that this is the right approach. Of course I can somehow adjust the parser to check that if only one item is present in the range selection, just return it. But it's very opinionated and I'd like to avoid that (also think about the case when what you get is something like `[[{ "name": "foo" }]]`, should we also return the inner object of nested arrays...?).

If you don't mind, I think that we can close this issue.

**Comment by dym-sh** [comment]
hm.. i wanted to get a list of all `name` fields to pass down to git-mirroring script, and

``` sh
jql '[0][0:]"name"' org.json
```
and does not work either

**Comment by yamafaktory** [comment]
@dym-sh Based on the structure you have provided, those selectors won't work.

Let me first explain why. You data is the following:
```json
[
  {
    "id": 196701619,
    "node_id": "MDEwOlJlcG9zaXRvcnkxOTY3MDE2MTk=",
    "name": "tauri",
    "full_name": "tauri-apps/tauri",
    "html_url": "https://github.com/tauri-apps/tauri",
    "open_issues_count": 55,
    "forks": 51,
    "open_issues": 55,
    "watchers": 1629,
    "default_branch": "dev"
  },
  {
    "id": 206315614,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMDYzMTU2MTQ=",
    "name": "examples",
    "full_name": "tauri-apps/examples",
    "html_url": "https://github.com/tauri-apps/examples",
    "open_issues_count": 7,
    "forks": 4,
    "open_issues": 7,
    "watchers": 6,
    "default_branch": "master"
  }
]
```
When applying `jql '[0][0:]."name"' org.json` what it does first with `[0]` is picking the index at position 0 of your top level array, so you get:

```json
 {
    "id": 196701619,
    "node_id": "MDEwOlJlcG9zaXRvcnkxOTY3MDE2MTk=",
    "name": "tauri",
    "full_name": "tauri-apps/tauri",
    "html_url": "https://github.com/tauri-apps/tauri",
    "open_issues_count": 55,
    "forks": 51,
    "open_issues": 55,
    "watchers": 1629,
    "default_branch": "dev"
  }
```
Then the next selector is `[0:]`, which is range selector. But that can't work since now we have an object not array...

The final selector is completely out scope anyway (`"name"`)...

What you want to do is the following:

```sh
jql '.|"name"' org.json
```
Here we apply a filter (https://github.com/yamafaktory/jql#filter) on the top level array directly.

Closing this issue as this is actually not one.

Feel free to ask if anything else pops up!

**Comment by dym-sh** [comment]
`.|"name"` did worked :smile:,

but this notation is the most confusing thing i saw since... [perl 9](https://urbit.org/docs/tutorials/hoon/hoon-syntax/)

feels counter-intuitive to all related technologies: shell, js (except `[0][0]`), and even css

**Comment by yamafaktory** [comment]
Well... `jq` does more or less the exact same thing, see the pipe https://stedolan.github.io/jq/manual/#Basicfilters. I did not intend to make this tool and its selectors behaving the same as JavaScript, etc. There's already plenty of other bigger CLI tools doing that for you. Sorry if you find it confusing :man_shrugging: .
