### ISSUE TITLE
Support for filtering children

### ISSUE THREAD

**Issue by keyneom** [yamafaktory/jql#39]
I might just not know how to do this, but I'm interested in being able to query for top level properties without seeing their children, is this possible?

I'm attempting to query a large json file that has an unknown structure to me.

**Comment by yamafaktory** [comment]
Hi @keyneom !

That's an interesting use case and the answer to your question is no, at the moment nothing has been implemented yet to support that.

Do you have an example of what you're trying to achieve?

**Comment by keyneom** [comment]
Yeah, what I'm trying to do is explore a very large json file. When I query the root, by the time anything gets output is already blown past the number of lines in my terminal history and it's difficult to determine how nested each property is.

An example of what I'd like to be able to do is take an input like this:

```
{
    "property1": {
        "subproperty1": "hello"
    }
}
```

And the desired output would be:
```
{
    "property1": {}
}
```
In particular it would be nice to be able to do without having to know beforehand what the names of the properties are, such as is done with the root selection.

**Comment by yamafaktory** [comment]
Ok, got it!

We'll need something new indeed. I can extend the grammar of the query parser to avoid walking down the JSON structure at a given level (can be the root level like in your example or at any desired level) and then return some truncated JSON selection.

I see a few challenging points here:
- Keep the feature simple (aim of this project / a counter example is something like `jq` which is super powerful but also bloated & buggy IMHO)
- Find the right grammar without breaking anything else (JSON syntax is more confusing then what folks expect, see https://tools.ietf.org/html/rfc8259#section-13)
- Decide what should be returned on any kind of selection (see next paragraph)

Regarding the last point, I see two options:

### Use `null` as truncated value
Based on your example:
```json
{
    "property1": null
}
```
The idea would be that, no matter what's the value of the selection - could be a string, an array, an object -, use `null` for truncate.

### Use the type as truncated value
Based on your example:
```json
{
    "property1": {}
}
```
Another example (let's keep it at the top level for now):
```json
{
    "a": 3
}
```
Or:
```json
{
    "a": "foo"
}
```
Or even:
```json
{
    "a": null
}
```
Would stay unchanged, since the values a simple primitives.

But something like:
```json
{
  "a": [{ "foo": 1 }, { "bar": 2 }]
}
```
Would become:
```json
{
  "a": []
}
```

The main benefit I see with this approach is that it's clear that what you're exploring is an array or an object (and then you can somehow continue to explore the JSON structure).

I'll think about it and keep you updated.

**Comment by yamafaktory** [comment]
Hi @keyneom !

I've just released a new version of the tool and you can now use the truncate selector, as described here https://github.com/yamafaktory/jql/#truncate.

It should fix your issue :rocket:, thanks for making `jql` better :bow: !

**Comment by keyneom** [comment]
Wow! You're awesome! I've been busy at work so I apologize about the slow response! I'll give it a try soon!
