### ISSUE TITLE
How does it compare to `jq`?

### ISSUE THREAD

**Issue by mkpankov** [yamafaktory/jql#44]
Is it expected to be a drop-in replacement? Or just inspired by it? Any difference besides being implemented in Rust?

**Comment by yamafaktory** [comment]
Hi @mkpankov!

The motivation behind this tool is neither to be a drop-in replacement nor something inspired by `jq`. `jq` API / features set is way beyond what `jql` tries to provide: a simple set of features that helps you dealing with JSON data. The grammar for the selectors is also quite different (it was slightly discussed here https://news.ycombinator.com/item?id=23316685).

Also `jql` is "presumably" faster than `jq`, on comparable features, see #43 (because it's using `serde` & `rayon` underneath, which are fast). `jq` also tries to be a safer alternative, it tries to provide meaningful error messages.

Regarding this issue, would you mind if we continue the thread in #43? Or do you see it differently?

**Comment by mkpankov** [comment]
Ah, thanks. It's clear enough, I'm closing this issue.

**Comment by pickfire** [comment]
But IMHO jql is takes more effort compared to jq on extracting stuff considering it needs to type so many double quotes.
