### ISSUE TITLE
Filtering doesn't work when key is assigned to a variable name.

### ISSUE THREAD

**Issue by krupatil** [yamafaktory/jql#58]
Can't get filtering work when key is assigned to a variable? 

```bash
$ FOO=\'\"foo\"\' && echo "{\"foo\":\"bar\"}" | jql -r "$FOO"
Empty group
$ echo "{\"foo\":\"bar\"}" | jql -r '"foo"'
bar
```

`jq` seems to be handling this very well.
```bash
$ FOO=".foo" && echo "{\"foo\":\"bar\"}" | jq -r "$FOO"
bar
$ echo "{\"foo\":\"bar\"}" | jq -r ".foo"
bar
```

I think, the input to the `jql` can be improved in similar way @yamafaktory.

**Comment by krupatil** [comment]
Update: This seem to work.
```bash
FOO=\"foo\" && echo "{\"foo\":\"bar\"}" | jql -r "${FOO}"
```

**Comment by yamafaktory** [comment]
@krupatil This is due to `jql` only accepting single quotes in the first place. You can see why here #56. As mentioned, I have no plan to change it as it will lead - in my opinion - to other bigger issues with parsing valid - but weird indeed! - JSON special characters.

If you don't mind, I'll close this issue. Fine for you?

**Comment by krupatil** [comment]
Thanks for the response @yamafaktory. Closing this issue.
