### ISSUE TITLE
Format the json output

### ISSUE THREAD

**Issue by blueray453** [yamafaktory/jql#69]
I have a return value like

```
[
  ".editorconfig",
  ".gitattributes",
  ".gitignore",
  ".revision-hash",
  ".travis.yml",
  ".version",
  "COPYING.md",
  "HACKING.md",
  "INSTALL.md",
  "Makefile",
  "README.md",
  "changelog.md",
  "docs",
  "docs/highlighters.md",
  "docs/highlighters",
  "docs/highlighters/brackets.md",
  "docs/highlighters/cursor.md",
  "docs/highlighters/line.md"
]
```
I want the return value to be like
```
.editorconfig
.gitattributes
.gitignore
.revision-hash
.travis.yml
.version
COPYING.md
HACKING.md
INSTALL.md
Makefile
README.md
changelog.md
docs
docs/highlighters.md
docs/highlighters
docs/highlighters/brackets.md
docs/highlighters/cursor.md
docs/highlighters/line.md
```
The current command I am using is:

curl -H "Accept: application/vnd.github.full+json" -H "Authorization: 7c258a9869f33c1e1e1f74fbb32f07c86cb5a75b" "https://api.github.com/repos/zsh-users/zsh-syntax-highlighting/git/trees/master?recursive=1" | jql '"tree"|"path"'

**Comment by yamafaktory** [comment]
Hi @blueray453.

This is not possible, `jql` only returns back JSON and what you want is definitely not JSON. The only exception to this is https://github.com/yamafaktory/jql#raw-output.

If you want more than JSON -> JSON, you might use something like `jq`.

Please let me know if this is unclear, otherwise I'll close the issue.

**Comment by blueray453** [comment]
Thank you very much.
